version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: rideforge-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: rideforge
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: rideforge-redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: rideforge-kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: redpanda
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: redpanda:9092

  redis:
    image: redis:7
    container_name: rideforge-redis
    ports:
      - "6379:6379"

volumes:
  postgres-data: